version: '3'
services:


  
  grafana: 
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=MendiolaValdez2004
    networks:
      - monitoring

networks:
  monitoring:
    external: true 
