global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'simulated_appliances'
    metrics_path: '/'
    scheme: 'https'
    static_configs:
      - targets: ['vi4ox3rl4b.execute-api.us-east-1.amazonaws.com']
